export const ListingData = [
{
    profileImage: "../../assets/BraidedLady.png",
    stylistName: "Braids by Becky",
    rating: 4.7,
    reviews: 20,
    address: "Don Mills, Toronto",
    tags: ['In-home Salon', 'Mobile'],
    services: "Box Braids, Knotless Braids, Weave, Faux Locs, Feed-in Braids + 13 more",
    like: false,
},
{
    profileImage: '../../assets/CelebrityLady.png', 
    stylistName: "Nella Studio",
    rating: 4.2,
    reviews: 20,
    address: "North York, Toronto",
    tags: ['In-home Salon', 'Mobile'],
    services: "Box Braids, Crotchet Braids, Weave, Faux Locs, Feed-in Braids + 13 more",
    like: true,
},
{
    profileImage: '../../assets/FreeAfro.png', 
    stylistName: "Clarisse Hair Salon",
    rating: 4.3,
    reviews: 12,
    address: "Etobicoke, Toronto",
    tags: ['In-home Salon', 'Mobile'],
    services: "Knotless Braids, Box Braids, Weave, Faux Locs, Feed-in Braids + 13 more",
    like: false,
},
{
    profileImage: '../../assets/WindyHair.png', 
    stylistName: "6ixBraids",
    rating: 3.8,
    reviews: 10,
    address: "Makssd, Donot",
    tags:["Doant", "Foloi"],
    services: "Knotless Braids, Box Braids, Weave, Faux Locs, Feed-in Braids + 13 more",
    like: true,
},
{
    profileImage: '../../assets/BraidedLady.png', 
    stylistName: "6ixBraids",
    rating: 3.8,
    reviews: 10,
    address: "Makssd, Donot",
    tags:["Doant", "Foloi"],
    services: "Knotless Braids, Box Braids, Weave, Faux Locs, Feed-in Braids + 13 more",
    like: true,
},

]