//Re-exporting components

export { default as BookingHeader } from "./ClientBookingPage/Header/Header";
export { default as AppointmentConfirmation } from "./StylistBookingPage/Modals/CreateAppointmentModals/AppointmentConfirmationModal/AppointmentConfirmation";
export { default as CustomService } from "./StylistBookingPage/Modals/CreateAppointmentModals/CustomServiceModal/CustomService";
export { default as NormalService } from "./StylistBookingPage/Modals/CreateAppointmentModals/NormalServiceModal/NormalService";
export { default as Schedule } from "./StylistBookingPage/Scheduler/Scheduler";
export { default as ErrorBoundary } from "./ErrorBoundary/ErrorBoundary";
export  { default as InfoForm } from "./StylistBookingPage/Modals/CreateAppointmentModals/ClientInfoFormModal/InfoForm";
export { default as Client } from "../pages/Client";
export { default as ClientProfile } from "../pages/ClientProfile";
export { default as Home } from "../pages/Home";
export { default as Stylist } from "../pages/Stylist";
export { default as StylistProfile } from "../pages/StylistProfile";
export { default as ErrorPage } from "./404Page/404Page";
export { default as ClientHeader } from "./Client/ClientHeader/ClientHeader";
export { default as ClientHero } from "./Client/ClientHero/ClientHero";
export { default as Cancellation } from "./ClientBookingPage/CancellationPage/Cancellation";
export { default as CancelModal } from "./ClientBookingPage/CancelModal/CancelModal";
export { default as ConfirmPage } from "./ClientBookingPage/ConfirmPage/ConfirmPage";
export { default as BookingHeaderClient } from "./ClientBookingPage/Header/Header";
export { default as PayPage } from "./ClientBookingPage/Pay/PayPage";
export { default as PolicyModalBooking } from "./ClientBookingPage/PolicyModal/Policy";
export { default as ReschedulePage } from "./ClientBookingPage/ReschedulePage/ReschedulePage";
export { default as StepOneBooking } from "./ClientBookingPage/StepOneBooking/StepOne";
export { default as StepTwoBooking } from "./ClientBookingPage/StepTwoBooking/StepTwo";
export { default as TimeRescheduler } from "./ClientBookingPage/TimeScheduler/TimeRescheduler";
export { default as AboutFilled } from "./ClientProfilePage/AboutSection/AboutFilled";
export { default as AddOnFilled } from "./ClientProfilePage/Add-OnSection/AddOnFilled";
export { default as Gallery } from "./ClientProfilePage/GallerySection/Gallery";
export { default as ClientSecHeader } from "./ClientProfilePage/HeaderSection/ClientSecHeader";
export { default as LocationFilled } from "./ClientProfilePage/LocationSection/LocationFilled";
export { default as PriceBar } from "./ClientProfilePage/PriceBar/PriceBar";
export { default as ProfileId } from "./ClientProfilePage/ProfileIdSection/ProfileId";
export { default as Reviewed } from "./ClientProfilePage/ReviewSection/Reviewed/Reviewed";
export { default as ReviewFilled } from "./ClientProfilePage/ReviewSection/ReviewFilled/ReviewFilled";
export { default as ServiceFilled } from "./ClientProfilePage/ServiceSection/ServiceFilled";
export { OnboardClient, StepFiveClient, StepFourClient, StepOneClient, StepThreeClient, StepTwoClient } from "./Onboarding/OnboardingClient/OnboardClient";
export { default as OnboardingStylistIntro } from "./Onboarding/OnboardingStylist/OnboardingStylistIntro";
export { default as IdUpload } from "./Onboarding/OnboardingStylist/StepFiveStylist/IdUpload/IdUpload";
export { default as LicenseQtn } from "./Onboarding/OnboardingStylist/StepFiveStylist/License/LicenseQtn";
export { default as LicenseUpload } from "./Onboarding/OnboardingStylist/StepFiveStylist/License/LicenseUpload";
export { default as BusinessHour } from "./Onboarding/OnboardingStylist/StepFourStylist/BusinessHour/BusinessHour";
export { BusinessModal } from "./Onboarding/OnboardingStylist/StepFourStylist/BusinessModal/BusinessModal";
export { default as BusinessPage } from "./Onboarding/OnboardingStylist/StepFourStylist/BusinessPage/BusinessPage";
export { default as CompletedStylist } from "./Onboarding/OnboardingStylist/StepSixStylist/CompletedStylist";
export { default as OnboardStylistForm } from "./Onboarding/OnboardingStylist/StepThreeStylist/OnboardStylistForm";
export { default as StepTwoStylist } from "./Onboarding/OnboardingStylist/StepTwoStylist/StepTwoStylist";
export { StylistConfirmationAdvanced, StylistConfirmationEstablished, StylistConfirmationExceptional, StylistConfirmationMajor } from "./Onboarding/OnboardingStylist/StepTwoStylist/StylistConfirmation";
export { default as BlogSection } from "./Sections/BlogSection/BlogSection";
export { default as BottomNavClient } from "./Sections/BottomNav/BottomNavClient";
export { default as BottomNavStylist } from "./Sections/BottomNav/BottomNavStylist";
export { default as ContactModal } from "./Sections/ContactModal/Contact";
export { default as Explore } from "./Sections/Explore/Explore";
export { default as Feedback } from "./Sections/Feedback/Feedback";
export { default as Footer } from "./Sections/Footer/Footer";
export { default as GetStartedModal } from "./Sections/GetStartedModal/GetStarted";
export { default as Header } from "./Sections/Header/Header";
export { default as Hero } from "./Sections/Hero/Hero";
export { default as Join } from "./Sections/Join/Join";
export { default as LoginModal } from "./Sections/LoginModal/Login";
export { default as SignupModal } from "./Sections/SignupModal/Signup";
export { default as SupportClient } from "./Sections/Support/SupportClient";
export { default as SupportStylist } from "./Sections/Support/SupportStylist";
export { default as Work } from "./Sections/Work/Work";
export { default as AppointmentSection } from "./StylistBookingPage/Appointment/AppointmentSection";
export { default as BookingHeaderStylist } from "./StylistBookingPage/BookingHeader/BookingHeader";
export { default as BookingPage } from "./StylistBookingPage/BookingPage/BookingPage";
export { default as ManageBookings } from "./StylistBookingPage/ManageBookingsPage/ManageBookings";
export { default as DeclineAppointment } from "./StylistBookingPage/ManageBookingsPage/DeclineAppointment";
export { default as PastAppointments } from "./StylistBookingPage/ManageBookingsPage/PastAppointments";
export { default as UpcomingAppointment } from "./StylistBookingPage/ManageBookingsPage/UpcomingAppointment";
export { default as AppointmentDetails } from "./StylistBookingPage/Modals/AppointmentDetailsModal/AppointmentDetails";
export { default as CancelAppointment } from "./StylistBookingPage/Modals/AppointmentDetailsModal/CancelAppointment";
export { default as DateReschedule } from "./StylistBookingPage/Modals/AppointmentDetailsModal/DateReschedule";
export { default as CreateAppointment } from "./StylistBookingPage/Modals/CreateAppointmentModals/AppointementStepOneModal/CreateAppointment";
export { DeclareNoShow, default as DuringAppointment } from "./StylistBookingPage/Modals/DuringAppointmentModal/DuringAppointment";
export { default as UpcomingBookings } from "./StylistBookingPage/UpcomingBookings/UpcomingBookings";
export { default as Placeholders } from "./StylistProfilePage/PlaceholderContent/Placeholders";
export { default as AboutModal } from "./StylistProfilePage/StylistProfileModals/AboutStylistModal/AboutModal";
export { default as AddOnModal } from "./StylistProfilePage/StylistProfileModals/Add-OnModal/AddOnModal";
export { default as Backdrop } from "./StylistProfilePage/StylistProfileModals/Backdrop/Backdrop";
export { default as DeletePicModal } from "./StylistProfilePage/StylistProfileModals/Delete/Delete";
export { default as GalleryModal } from "./StylistProfilePage/StylistProfileModals/GalleryModal/GalleryModal";
export { default as DisplayProfile } from "./StylistProfilePage/StylistProfileModals/ProfilePicModal/DisplayProfile";
export { default as ProfilePicture } from "./StylistProfilePage/StylistProfileModals/ProfilePicModal/ProfilePic";
export { default as PolicyModal } from "./StylistProfilePage/StylistProfileModals/RulesPolicyModal/PolicyModal";
export { default as ServiceModal } from "./StylistProfilePage/StylistProfileModals/ServiceModal/ServiceModal";
export { default as Variant } from "./StylistProfilePage/StylistProfileModals/ServiceModal/Variant";
export { default as VariantTable } from "./StylistProfilePage/StylistProfileModals/ServiceModal/VariantTable";
export { default as TagsInput } from "./StylistProfilePage/StylistProfileModals/TagsInput/TagsInput";
export { default as UploadPhoto } from "./StylistProfilePage/StylistProfileModals/UploadPhotoModal/UploadPhoto";
export { default as StylistHeader } from "./StylistProps/StylistHeader/StylistHeader";




